go_import_path: github.com/jizuscreed/githubmosaic

language: go

go:
  - 1.7.x
install:
- # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).

